module.exports = {
  // 获取webpack内存中的文件(manifest)
  EVENT_WEBPACK_MEMORY_MANIFEST: 'EVENT_WEBPACK_MEMORY_MANIFEST',
  // 构建状态是否已经就绪
  EVENT_WEBPACK_BUILD_READY: 'EVENT_WEBPACK_BUILD_READY',
  // 获取构建代理的配置
  EVENT_WEBPACK_BUILD_PROXY_CONFIG: 'EVENT_WEBPACK_BUILD_PROXY_CONFIG',
};
